// Generated by CoffeeScript 2.1.1
var Phaser, game;

Phaser = require('./lib/main.js');

game = new Phaser.Game(500, 500, Phaser.HEADLESS);

game.state.add('main', {
  preload: function() {
    this.game.time.desiredFps = 10;
    return this.game.updateLogic();
  },
  update: function() {
    return console.log('frame');
  }
});

game.state.start('main');
